INSERT INTO papier_wartosciowy (symbol, nazwa, typ, poziom_ryzyka) VALUES 
('AAPL', 'Apple Inc.', 'akcje', 3),
('TSLA', 'Tesla Inc.', 'akcje', 4),
('GOOG', 'Alphabet Inc.', 'akcje', 3),
('AMZN', 'Amazon.com', 'akcje', 3),
('NFLX', 'Netflix Inc.', 'akcje', 4),
('BA', 'Boeing Co.', 'akcje', 3),
('JNJ', 'Johnson & Johnson', 'akcje', 2),
('MSFT', 'Microsoft Corp.', 'akcje', 3),
('NVDA', 'NVIDIA Corp.', 'akcje', 3),
('XOM', 'ExxonMobil', 'akcje', 2),
('UBS', 'UBS Group', 'obligacje', 1),
('GS', 'Goldman Sachs', 'obligacje', 2),
('VOO', 'Vanguard S&P 500', 'etf', 2),
('TLT', '20+ Year Treasury', 'etf', 1),
('SPY', 'SPDR S&P 500', 'etf', 2),
('QQQ', 'Powershares QQQ', 'etf', 3),
('XLRE', 'Real Estate Sel Sect', 'etf', 3),
('ARKK', 'ARK Innovation', 'fundusze', 4),
('FXAIX', 'Fidelity 500 Index', 'fundusze', 2),
('CAI', 'Capital Income', 'fundusze', 2);